version: "2"

volumes:
  mattermost-files-data:
    external: true
  mattermost-db-data:
    external: true

services:

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - mattermost-db-data:/var/lib/postgresql/data/
      - ./backup/:/backup/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    restart: always
    
  mattermost:
    build:
      context: .
    image: vukor/mattermost
    container_name: mattermost
    ports:
      - 8065:8065
    volumes:
      - mattermost-files-data:/home/m/mattermost/data/
    depends_on:
      - postgres
    restart: always

